### ISSUE TITLE
Popover floating issue

### ISSUE THREAD

**Issue by alexzhang1030** [RSSNext/Follow#896]
### Describe the bug

Account popover is not auto-closed when using shortcut/menubar to open preferences modal.

### Environment

**App Version**: 0.0.1-alpha.19
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.0.1-alpha.19 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
**Env**: electron
**Browser**: Chrome

### Feed Info

UI issue

### Reproduction Video

https://github.com/user-attachments/assets/77eba8f8-6e45-48e6-b8f1-f2a2cafa30c4

### App Type

Electron / App

### Version

0.0.1-alpha.19

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Innei** [comment]
@lawvs After adjusting the Modal's z-index, you should revisit these global popups. For example, ContextMenu Or DropdownMenu

**Comment by Innei** [comment]
Radix bulitin dropdown menu z-index is 50.
![CleanShot 2024-10-15 at 8  12 09@2x](https://github.com/user-attachments/assets/d38c9434-195c-4cb1-b225-8b85bb598254)


Should we insist on not using z-index and then patch the radix package, or redefine the z-index hierarchy specification instead of directly removing z-index? I believe the latter is more suitable.

**Comment by Innei** [comment]
![CleanShot 2024-10-15 at 8  18 55@2x](https://github.com/user-attachments/assets/51cd48a8-c2a8-4b87-b609-732dfe2c90fa)
